### ISSUE TITLE
Implement D8 initialization for civicrm-setup

### ISSUE THREAD

**Issue by monishdeb** [civicrm/civicrm-setup#10]
__Background__: When installing on Drupal 8, settings such as DSN and locale should be autodetected.
__Task__: 

* Copy `plugins/init/Drupal.civi-setup.php` or `plugins/init/WordPress.civi-setup.php`
* Create `Drupal8.civi-setup.php`
* Adapt for D8. For source material on how to detect things like DSN, look at `civicrm-drupal@8.x-master` in `civicrm.install` / `drush.civicrm.inc`.

**Comment by monishdeb** [comment]
@totten can you please check my PR https://github.com/civicrm/civicrm-setup/pull/11 ?

**Comment by totten** [comment]
I've merged but haven't actually tested on D8. We should re-test in a bit (once more parts are merged-in).

**Comment by totten** [comment]
duplicates https://lab.civicrm.org/dev/drupal/issues/2
